# Deploy serverless function
steps:
  # Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - my-http-function
      - --region=us-west2
      - --source=serverless
      - --trigger-http
      - --runtime=python312
      - --entry-point=hello
options:
  logging: NONE